CREATE TABLE [dbo].[Demand_History_Interface](
[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
analysis_id [numeric](18, 0),
Proper_company_code [nvarchar](50) NOT NULL,
Region_code_management_group [nvarchar](50) NOT NULL,
Management_group_code [nvarchar](50) NOT NULL,
Reference_date [nvarchar](50) NOT NULL,
Analysis_code [nvarchar](50) NOT NULL,
Region_code_management_unit [nvarchar](50) NOT NULL,
Management_unit_code [nvarchar](50) NOT NULL,
Item_code [nvarchar](50) NOT NULL,
Description [nvarchar](255) NOT NULL,
Demand_classification_01 [nvarchar](50) NOT NULL,
Demand_classification_02 [nvarchar](50) NOT NULL,
Demand_classification_03 [nvarchar](50) NOT NULL,
Demand_classification_04 [nvarchar](50) NOT NULL,
Demand_classification_05 [nvarchar](50) NOT NULL,
Bucket [nvarchar](50) NOT NULL,
Date [nvarchar](50) NOT NULL,
Demand_type [nvarchar](50) NOT NULL,
Quantity [nvarchar](50) NOT NULL,
Unity_of_measure [nvarchar](50) NOT NULL,
Client_company_code [nvarchar](50) NOT NULL,
Client_company_name [nvarchar](50) NOT NULL,
Client_unit_code [nvarchar](50) NOT NULL,
Client_unit_description [nvarchar](50) NOT NULL,
Plant_code [nvarchar](50) NOT NULL,
Plant_description [nvarchar](50) NOT NULL,
Production_line_code [nvarchar](50) NOT NULL,
Production_line_description [nvarchar](50) NOT NULL,
Product_code [nvarchar](50) NOT NULL,
Product_description [nvarchar](255) NOT NULL,
Region_code_origin [nvarchar](50) NOT NULL,
Management_unit_code_origin [nvarchar](50) NOT NULL,
Management_unit_description_origin [nvarchar](255) NOT NULL,
Demand_category_classification_origin_01 [nvarchar](50) NOT NULL,
Demand_category_classification_origin_02 [nvarchar](50) NOT NULL,
Demand_category_classification_origin_03 [nvarchar](50) NOT NULL,
Demand_category_classification_origin_04 [nvarchar](50) NOT NULL,
Demand_category_classification_origin_05 [nvarchar](50) NOT NULL,
Validation_item_code [bit] NULL,
Validation_item_description [bit] NULL,
Validation_demand_classification [bit] NULL,
Validation_bucket [bit] NULL,
Validation_date [bit] NULL,
Validation_demand_type [bit] NULL,
Validation_quantity [bit] NULL,
Validation_unit_of_measure [bit] NULL,
Validation_client_company_code [bit] NULL,
Validation_client_company_name [bit] NULL,
Validation_client_unit_code [bit] NULL,
Validation_client_unit_description [bit] NULL,
Validation_product_code [bit] NULL,
Validation_product_description [bit] NULL,
Validation_region_code [bit] NULL,
Validation_management_unit_code [bit] NULL
) ON [PRIMARY]
GO
