USE [Proper_Base]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ ](
	[Id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[spu_id] [numeric](18, 0) NULL,
	[Unit_cost_average] [numeric](18, 2) NULL,
	[Unit_cost_replenishment] [numeric](18, 2) NULL,
	[Unit_cost_alternate] [numeric](18, 2) NULL,
	[Default_duration_Development] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_Development] [nvarchar](2) NULL,
	[Default_duration_Pre_launch] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_Pre_launch] [nvarchar](2) NULL,
	[Default_duration_Launch] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_Launch] [nvarchar](2) NULL,
	[Default_duration_Maturity] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_Maturity] [nvarchar](2) NULL,
	[Default_duration_Demand_level_change] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_demand_level_change] [nvarchar](2) NULL,
	[Default_duration_Exit] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_Exit] [nvarchar](2) NULL,
	[Default_duration_Supply_inactivity] [numeric](18, 0) NULL,
	[Duration_unit_of_measure_supply_inactivity] [nvarchar](2) NULL,
	[Lead_time_unit] [nvarchar](2) NULL,
	[Lead_time_Minimum_] [numeric](18, 4) NULL,
	[Lead_time_average] [numeric](18, 4) NULL,
	[Lead_time_Maximum_] [numeric](18, 4) NULL,
	[Lead_time_standard_deviation] [numeric](18, 4) NULL,
	[Lot_size_Minimum_] [numeric](18, 4) NULL,
	[Lot_size_multiple] [numeric](18, 4) NULL,
	[Grouping_item_code] [nvarchar](50) NULL,
	[Grouping_item_id] [numeric](18, 0) NULL,
	[Grouping_share] [numeric](18, 4) NULL,
	[Local_independent_demand_origin] [nvarchar](2) NULL,
	[Local_dependent_estimated_demand_origin] [nvarchar](2) NULL,
	[Local_dependent_demand_origin] [nvarchar](2) NULL,
	[Transferred_estimated_demand_origin] [nvarchar](2) NULL,
	[Transferred_demand_origin] [nvarchar](2) NULL,
	[First_demand] [datetime] NULL,
	[Last_demand] [datetime] NULL,
	[Relevant_history_begin] [datetime] NULL,
	[Relevant_history_end] [datetime] NULL,
	[Relevant_history_duration] [numeric](18, 0) NULL,
	[Relevant_history_duration_unit_of_measure] [nvarchar](2) NULL,
	[outlier_criteria] [nvarchar](2) NULL,
	[Upper_outlier_automatic_limitation] [nvarchar](2) NULL,
	[Upper_outlier_limit] [numeric](18, 4) NULL,
	[Lower_outlier_automatic_limitation] [nvarchar](2) NULL,
	[Lower_outlier_limit] [numeric](18, 4) NULL,
	[Proper_Stock_analysis] [nvarchar](2) NULL,
	[Proper_Action_monitoring] [nvarchar](2) NULL,
	[Management_type] [nvarchar](2) NULL,
	[Planning_method] [nvarchar](2) NULL,
	[Criticality_criteria_01_grade] [numeric](18, 4) NULL,
	[Criticality_criteria_02_grade] [numeric](18, 4) NULL,
	[Criticality_criteria_03_grade] [numeric](18, 4) NULL,
	[Criticality_criteria_04_grade] [numeric](18, 4) NULL,
	[Criticality_criteria_05_grade] [numeric](18, 4) NULL,
	[Maximum_forecast_error_application] [nvarchar](2) NULL,
	[Maximum_forecast_error] [numeric](18, 4) NULL,
	[Minimum_safety_stock_coverage] [numeric](18, 4) NULL,
	[Minimum_safety_stock_coverage_unit_of_measure] [nvarchar](2) NULL,
	[Maximum_safety_stock_coverage] [numeric](18, 4) NULL,
	[Maximum_safety_stock_coverage_unit_of_measure] [nvarchar](2) NULL,
	[Service_level] [numeric](18, 4) NULL,
	[Safety_stock] [numeric](18, 4) NULL,
	[Qualitative_criteria_1_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_2_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_3_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_4_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_5_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_6_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_7_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_8_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_9_grade] [numeric](18, 4) NULL,
	[Qualitative_criteria_10_grade] [numeric](18, 4) NULL
) ON [PRIMARY]
GO


